:toc-placement!:
:imagesdir: ./

== Chapter 9. Error Handling  

In this chapter I'll explain you how to handle run-time errors, which in Java are called _exceptions_.

Say you forgot to write one closing curly brace in your Java code. This will result in the compilation error that can be fixed easily. But there are so called _run-time errors_, when all of a sudden your program stops working properly.

For example, a Java class reads a file with the game scores. What’s going to happen if someone will delete this file? Will the program crash with a scary error message, or will it stay alive displaying a user friendly message like this one: _Dear friend, for some reason I could not read the file scores.txt. Please make sure that the file exists?_ This is an example of a situation when Java compiler won't be able to help - the Java syntax was written properly. 

You should make your programs ready for unexpected situations. you should foresee what might go wrong when the program will be running, and what to do if something went wrong. In many programming languages the programmer decides if he wants to add error processing code to a program. But in many cases Java forces you to include error processing code, otherwise the programs will not even compile.

Runtime errors in Java are called exceptions, and error processing is called _exception handling_. You have to place code that may produce errors in so-called `try/catch` block. It’s as if you’re saying to JVM the following: _Try to read the file with scores, but if something happens, catch the error and execute the code that will deal with it:_

[source, Java]
----
try{
  fileScores.read();     
}
catch (IOException e){
  System.out.println(
       "Dear friend,I could not read the file scores.txt");
}
----

We’ll learn how to work with files in Chapter 10, but at this point I'd like to introduce a new term _I/O_ or _input/output_. Read and write operations (from/to disk or other device) are also known as I/O operations, and the class `IOException` is a class that contains information about input/output errors.

In the Java world, a method _throws an exception_ in case of a runtime error. Different exceptions will be thrown for different type of errors.  If the `catch` block exists in the program for this particular type of an error, it will be caught and the program will jump into the `catch` block  to execute the code located there. The program will stay alive, and this exception is considered to be taken care of.  

The print statement from the code above will be executed only in case of the file read error. 

=== Reading the Stack Trace

If an unexpected exception occurs that is not handled by the program, it prints a multi-line error message on the screen. Such message is called stack trace. If your program  called several methods before it ran into a problem, the _stack trace_ can help you to trace the program, and find the line that have caused the error.

We know that dividing by zero is illegal. But, for the illustration purposes, I wrote a program `TestStackTrace` that divides by zero on purpose  (line numbers are not the part of the code).

[source, Java]
----
1 class TestStackTrace{    
2  TestStackTrace()
3   {
4    divideByZero();
5   }
6
7  int divideByZero()
8   {
9      return 25/0;
10  }
11
12  static void main(String[] args)
13  {
14    new TestStackTrace();
15  }
16 }
----

The output of this program shows the sequence of method calls that were made up to the moment when the run-time error had happened. Start reading this output from the last line going up. 

`Exception in thread "main"`
`java.lang.ArithmeticException: / by zero`
   `at TestStackTrace.divideByZero(TestStackTrace.java:9)`
   `at TestStackTrace.<init>(TestStackTrace.java:4)`
   `at TestStackTrace.main(TestStackTrace.java:14)`

This means that the program started in the method `main`, then went to `init` which is a constructor, and then called the method `divideByZero`. The numbers 14, 4 and 9 show in which lines of the program these methods were called. After that, an `ArithmeticException` was thrown –the line number nine tried to divide by zero. 

=== Genealogical Tree of Exceptions 

Exceptions in Java are also classes, and some of them are shown in the following inheritance tree:
 
[[FIG9-1]]
.Exceptions Hierarchy
image::images/fig_9_01.png[]


Subclasses of the class `Exception` are called _checked exceptions_ and you must process them  in your code.

Subclasses of the class `Error` are fatal JVM errors and the running program can’t handle them.

The `TooManyBikesException` is an example of exception that can be created by a programmer. 

How a programmer is supposed to know in advance if some Java method may throw an exception and that a `try/catch` block should be used?  Not to worry, if you call a method that may throw an exception, Java compiler will print an error message similar to this one: 

`"ScoreReader.java":  unreported exception: java.io.IOException; must be ``caught or declared to be thrown at line 57`

Of course you are welcome to read Java documentation that describes exceptions that may be thrown by any particular  method.  The rest of this chapter will explain how to deal with these exceptions.

=== Try/Catch Block

There are five Java keywords that can be used for error handling: `try`, `catch`, `finally`, `throw`, and `throws`.

After one `try` block you may put several `catch` blocks, if you believe that more than one error may happen. For example, when a program tries to read a file, the file may not be there, and you’ll get the `FileNotFoundException`, or the file is there, but the code keeps reading the file after reaching the end of  file – this generates `EOFException`. The next code fragment  will print messages in plain English if the program can’t find a file with game scores or reached the end of the file. For any other read errors it’ll print the message _Problem reading_ file and a technical description of the error. 

[source, Java]
----
public void getScores(){ 
 try{
    fileScores.read();
    System.out.println(“Scores loaded successfully”); 
 }catch(FileNotFoundException e){
     System.out.println(“Can not find file Scores”);
 }catch(EOFException e1){
      System.out.println(“Reached end of file”);
 }catch(IOException e2){
      System.out.println(“Problem reading  file “ + 
                                    e2.getMessage());
 }
}
----

If the method `read` fails, the program jumps over the line `println`  and tries to land in the `catch` block that matches the error. If it finds such block, the appropriate methid `println` will be executed, but if the matching catch block is not found, the method `getScores` will re-throw this exception to its caller.

If you write several `catch` blocks, you may need to place them in a particular order if these exceptions are inherited from each other. For example, since the `EOFException` is a subclass of the `IOException`, you have to put the `catch` block for the subclass first.  If you would put the `catch` for `IOException` first, the program would never reach the `FileNotFound` or `EOFException`, because the first `catch` would intercept them.

Lazybones would program the method `getScores` just like this:

[source, Java]
----
public void getScores(){ 
 try{
  fileScores.read();
 }catch(Exception e){
  System.out.println(“Problem reading  file ”+      
                                      e.getMessage());
   }
}
----

This is an example of a bad style of Java coding. When you write a program, always remember that someone else may read it, and you don’t want to be ashamed of your code.

Catch blocks receive an instance of the object `Exception` that contains a short explanation of a problem, and its method `getMessage` will return this info. Sometimes, if the description of an error is not clear, try the method `toString` instead:

[source, Java]
----
catch(Exception e){
 System.out.println(“Problem reading file ”+ e.toString());
}
----

If you need more detailed information about the exception, use the method `printStackTrace`. It will print the sequence of  method calls that lead to this exception  similar to an example from  the section _Reading Stack Trace_.

Let's try to “kill” the calculator program from Chapter 6. Run the class Calculator and enter from the keyboard the charactes _abc_. Press any of the action buttons, and you’ll see on the console screen something like this:

[source, Java]
----
java.lang.NumberFormatException: For input string: "abc"
   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
   at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1213)
   at java.lang.Double.parseDouble(Double.java:202)
   at CalculatorEngine.actionPerformed(CalculatorEngine.java:27)
   at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1764)
----

This was an example of a non-handled exception. The class `CalculatorEngine` has the following line in its method `actionPerformed`:

`displayValue= Double.parseDouble(dispFieldText);`

If the variable `dispFieldTest` has not a numeric value,  the method `parseDouble` will not be anle to convert it to the `double` data type and will throw a `NumberFormatException`.

Let's handle this exception and display an error message that will explain the problem to the user.  The line with `parseDouble` has to be placed in a `try/catch` block, and Eclipse will help you with this. Highlight this line and right-click on it with the mouse. In the popup menu select the items _Source_ and _Surround with try/catch block_. Voila! The code is changed:

[source, Java]
----
try {
   displayValue= Double.parseDouble(dispFieldText);
} catch (NumberFormatException e1) {
   // TODO Auto-generated catch block
   e1.printStackTrace();
}
----

Replace the `printStackTrace` line with the following:

[source, Java]
----     
javax.swing.JOptionPane.showConfirmDialog(null,
   "Please enter a Number", "Wrong input",
   javax.swing.JOptionPane.PLAIN_MESSAGE);
return;
----

We’ve gotten rid of the scary stack trace error messages, and displayed a simple to understand  message _Please enter a Number_. Now the `NumberFormatException` is handled.

=== The keyword `throws`

In some cases, it makes more sense to handle the exception not in the method where it happened, but in the method’s caller. 
In such cases the method signature has to declare (warn) that it may throw a particular exception. This is done using a special keyword `throws`. Let’s use the same example that reads a file. Since the method `read` may throw an `IOException`, you should either handle or declare it. In the next example we are  going to declare that the method `getAllScores` may throw an IOException: 

[source, Java]
----
class MySuperGame{

  void getAllScores() throws IOException{
   // …    
   // Do not use try/catch  if you are 
   // not handling exceptions in this method
   file.read();
  }

  public static void main(String[] args){
    MySuperGame msg = new MySuperGame();  
    System.out.println(“List of Scores”);

    try{
     // Since the  getAllScores()declares exception,       
     // we handle  it over here
       msg.getAllScores();  

    }catch(IOException e){
       System.out.println(
       "Sorry, the list of scores is not available");
    }
 }
----

Since we are not even trying to catch exceptions here, the `IOException` will be  _propagated_ from the `getAllScores` to its caller - the method `main`. Now the main method has to handle this exception.

=== The Keyword `finally`

Any code within a `try/catch` block can end in one of the following ways:

* The code inside the `try` block successfully ended and the program continues.
* The code inside the `try` block runs into a `return` statement and the method is exited.
* The code in the `try` block throws an exception and control goes to the matching `catch` block, which either handles the error and the method execution continues, or it re-throws the exception to the caller of this method.

If there is a piece of code that must be executed no matter what, put it under the keyword `finally`:

[source, Java]
----
try{
   file.read();
}catch(Exception e){
   printStackTrace();
}finally{
  // the code that must always be executed 
  // goes here, for example file.close(); 
}

----

The code above has to close the file regardless of success or failure of the read operation. Usually, you can find the code that releases some computer resources in the block `finally`, for example, disconnection from a network or file closing.

If you are not planning to handle exceptions in the current method, they will be propagated to the caller. In this case, you can use the `finally` even without a `catch` block:

[source, Java]
----
void myMethod() throws IOException{
 try{
   // your code that reads a file goes here
 }
 finally{
   // your code that closes the file  goes here
 }
}
----

=== The Keyword `throw`

If an exception has happened in a method, but you believe that the caller should handle it, just re-throw it to the method’s caller. Sometimes, you might want to catch one exception but re-throw another one with a different description of the error like in the code snippet below.  

The statement `throw` is used to throw Java objects. The object that a program throws must be _throwable_. This means that you can only throw objects that are direct or indirect subclasses of the class `Throwable`, and all Java exceptions are its subclasses. 

[[FIG9-3]]
.Throwing exceptions
image::images/fig_9_02.png[]

The next code fragment shows how the method `getAllScores()` catches an `IOException` and creates a new `Exception` object with a more friendly description of the error, and re-throws it to the method `main()`.  Now the method `main()` won’t compile unless you put the line that calls `getAllScores` in the `try/catch` block, because this method may throw an `Exception` and it should be either handled or re-thrown again. The method `main` should not throw any exceptions, that’s why it should handle it.

[source, Java]
----
class ScoreList{
   // Additional code is needed to compile this class

   static void getAllScores() throws Exception{
     try{
      file.read();//this line may throw an exception
     } catch (IOException e) {
      throw new  Exception (
      "Dear Friend, the file Scores has problems");
     }
   }

  public static void main(String[] args){
    System.out.println("Scores");

   try{
       getAllScores();
   }
   catch(Exception e1){
        System.out.println(e1.getMessage());
   }
 }
} 
----

In case of a file error,  the main method will handle it,  and  the `e1.getMessage`   will return the _Dear Friend…_ message.   

[[FIG8-3]]
.Showing a user-friendly message
image::images/fig_8_03.png[]

=== Creating New Exceptions 

Programmers could also create new  exception classes  that did not exist in Java before.  Such classes have to derive from one of the Java exception classes.  Let’s say you are in business of selling bikes and need to _validate_ customer orders. Different number of bikes can fit in your small truck depending on the model. For example, you can fit no more than three FireBird bikes in your truck. Create a new subclass of `Exception` called `TooManyBikesException`, and if someone tries to order more than three of these bikes,  throw the this exception: 

[source, Java]
----
class TooManyBikesException extends Exception{

  // Constructor 
  TooManyBikesException (){
  // Just call the constructor of the superclass
  // and pass to it the error message to display
  super("Can't ship this many bikes in one shipment.");      
  }  
}
----

This class has only a constructor that takes the message describing this error and gives it to its superclass for  storage. When some `catch` block receives this exception it can find out what exactly has happened by calling the method `getMessage`. 

Imagine that a user selects on the `OrderWindow` several bicycles of some model and hits the button _Place Order_. As you know from Chapter 6, this action will result in call to `actionPerformed` that will check if the order can be  delivered.  The next code example shows how the method `checkOrder` of this window declares that it can throw `TooManyBikesException`.  If the order won’t fit in the truck, this method throws the exception, the catch block  intercepts it and displays an error message in the text field on the window.

[source, Java]
----
class OrderWindow implements ActionListener{
// The code to create window components is needed here. 

// The user clicked on the button Place Order
   String selectedModel = txtFieldModel.getText();
   String selectedQuantity =  
                          txtFieldQuantity.getText();
   int quantity = Integer.parseInt(selectedQuantity);   

  void actionPerformed(ActionEvent e){
    try{   
   bikeOrder.checkOrder("FireBird", quantity);
  //the next line will be skipped in case of exception
   txtFieldOrderConfirmation.setText(
                           "Your order is complete");   
   } catch(TooManyBikesException e){
    txtFieldOrderConfirmation.setText(e.getMessage());
   }                          
 }
 
 void checkOrder(String bikeModel, int quantity) 
                         throws TooManyBikesException{

//Write the code that checks if the requested //quantity of bikes of selected model will fit in the //truck. If they won't fit, do  the following: 

  throw new TooManyBikesException("Can not ship" + 
   quantity + " bikes of the model " + bikeModel +
                        " in one shipment" );
 }
}
----

In a perfect world, every program would work properly, but realistically we have to be ready for the unexpected situations. It really helps that Java forces you to write code that is prepared for  these situations.
For more detailed coverage of exceptions read Oracle's   http://docs.oracle.com/javase/tutorial/essential/exceptions/[lesson on exceptions].


=== Project


Create an application for placing bike orders. 